FROM alpine:3.21

WORKDIR /app

RUN mkdir -p /app/data
RUN apk add --no-cache tzdata ca-certificates

COPY dogecoin-relayer /app/dogecoin-relayer

EXPOSE 8080 4001 5001 50051

CMD ["/app/dogecoin-relayer", "-config", "/app/config/config.yaml"]
