// dogecoin.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: proto/dogecoin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BitcoinLightWallet_NewTransaction_FullMethodName      = "/proto.BitcoinLightWallet/NewTransaction"
	BitcoinLightWallet_QueryDepositAddress_FullMethodName = "/proto.BitcoinLightWallet/QueryDepositAddress"
)

// BitcoinLightWalletClient is the client API for BitcoinLightWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BitcoinLightWalletClient interface {
	NewTransaction(ctx context.Context, in *NewTransactionRequest, opts ...grpc.CallOption) (*NewTransactionResponse, error)
	QueryDepositAddress(ctx context.Context, in *QueryDepositAddressRequest, opts ...grpc.CallOption) (*QueryDepositAddressResponse, error)
}

type bitcoinLightWalletClient struct {
	cc grpc.ClientConnInterface
}

func NewBitcoinLightWalletClient(cc grpc.ClientConnInterface) BitcoinLightWalletClient {
	return &bitcoinLightWalletClient{cc}
}

func (c *bitcoinLightWalletClient) NewTransaction(ctx context.Context, in *NewTransactionRequest, opts ...grpc.CallOption) (*NewTransactionResponse, error) {
	out := new(NewTransactionResponse)
	err := c.cc.Invoke(ctx, BitcoinLightWallet_NewTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitcoinLightWalletClient) QueryDepositAddress(ctx context.Context, in *QueryDepositAddressRequest, opts ...grpc.CallOption) (*QueryDepositAddressResponse, error) {
	out := new(QueryDepositAddressResponse)
	err := c.cc.Invoke(ctx, BitcoinLightWallet_QueryDepositAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitcoinLightWalletServer is the server API for BitcoinLightWallet service.
// All implementations must embed UnimplementedBitcoinLightWalletServer
// for forward compatibility
type BitcoinLightWalletServer interface {
	NewTransaction(context.Context, *NewTransactionRequest) (*NewTransactionResponse, error)
	QueryDepositAddress(context.Context, *QueryDepositAddressRequest) (*QueryDepositAddressResponse, error)
	mustEmbedUnimplementedBitcoinLightWalletServer()
}

// UnimplementedBitcoinLightWalletServer must be embedded to have forward compatible implementations.
type UnimplementedBitcoinLightWalletServer struct {
}

func (UnimplementedBitcoinLightWalletServer) NewTransaction(context.Context, *NewTransactionRequest) (*NewTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTransaction not implemented")
}
func (UnimplementedBitcoinLightWalletServer) QueryDepositAddress(context.Context, *QueryDepositAddressRequest) (*QueryDepositAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDepositAddress not implemented")
}
func (UnimplementedBitcoinLightWalletServer) mustEmbedUnimplementedBitcoinLightWalletServer() {}

// UnsafeBitcoinLightWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BitcoinLightWalletServer will
// result in compilation errors.
type UnsafeBitcoinLightWalletServer interface {
	mustEmbedUnimplementedBitcoinLightWalletServer()
}

func RegisterBitcoinLightWalletServer(s grpc.ServiceRegistrar, srv BitcoinLightWalletServer) {
	s.RegisterService(&BitcoinLightWallet_ServiceDesc, srv)
}

func _BitcoinLightWallet_NewTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinLightWalletServer).NewTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BitcoinLightWallet_NewTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinLightWalletServer).NewTransaction(ctx, req.(*NewTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BitcoinLightWallet_QueryDepositAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDepositAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinLightWalletServer).QueryDepositAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BitcoinLightWallet_QueryDepositAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinLightWalletServer).QueryDepositAddress(ctx, req.(*QueryDepositAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BitcoinLightWallet_ServiceDesc is the grpc.ServiceDesc for BitcoinLightWallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BitcoinLightWallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BitcoinLightWallet",
	HandlerType: (*BitcoinLightWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTransaction",
			Handler:    _BitcoinLightWallet_NewTransaction_Handler,
		},
		{
			MethodName: "QueryDepositAddress",
			Handler:    _BitcoinLightWallet_QueryDepositAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dogecoin.proto",
}
