# config.yaml

log:
  level: "debug"

sqlite:
  folder: "/app/data"

gorm:
  log_level: "info" # optional: silent, error, warn, info
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # unit: second

p2p:
  enabled: true
  listen_addr: /ip4/0.0.0.0/tcp/4001
  bootstrap_peers:
    - /ip4/127.0.0.1/tcp/4001/p2p/QmS4ghgMgfFvqPjB4WKXHaN15ZyT4K4JY8Y8Y8Y8Y8
    - /ip4/127.0.0.1/tcp/4001/p2p/QmS4ghgMgfFvqPjB4WKXHaN15ZyT4K4JY8Y8Y8Y8Y8
  enable_mdns: true
  listen_wait_seconds: 30
  connection_wait_seconds: 120
  key_dir: "/app/p2p"

http:
  enabled: true
  port: 8080

doge:
  rpc_url: "http://localhost:18443"
  rpc_user: ""
  rpc_password: ""
  start_height: 0
  confirmations: 1
  network_type: "regtest"

scan:
  enabled: true
  interval: 60 # unit: second
  timeout: 30 # unit: second
  range: 1000
  confirmations: 1

consensus:
  enabled: true
  rpc: "https://testnet3.rpc.goat.network"
  chain_id: 48816
  contract_bridge: "0x0000000000000000000000000000000000000000"
  contract_manager: "0x0000000000000000000000000000000000000000"
  event_detection:
    enabled: true
    last_scanned_block: 10000
    confirmation_blocks: 2
    batch_size: 1000
    scan_interval_sec: 5

tss:
  enabled: true
  url: "http://localhost:8080"
  kdd: 10
